# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - go build -o cube-rmgeo.exe main.go
      - ./cube-rmgeo.exe -c config.json

  server:
    cmds:
      - go build -o cube-rmgeo.exe main.go
      - ./cube-rmgeo.exe -c config.json -s

  build-arm64:
    env:
      GOOS: linux
      GOARCH: arm64
    cmds:
      - go build -o cube-rmgeo main.go
